### ISSUE TITLE
Files in the root folder not copied & additionally folder created

### ISSUE THREAD

**Issue by Utility9298** [Seidlm/PowerShell-Backup-Script#11]
I just tested the v2 and got following:

The files in the root directory still don't get copied. 
![image](https://user-images.githubusercontent.com/87972749/128348763-ac813f43-bc62-4b1f-9899-e5f6bc25ea47.png)

Also there is an additionally folder created, but that is not needed because i choose the option for zip. 
![image](https://user-images.githubusercontent.com/87972749/128348865-a38440b6-04af-43dd-adec-457172b818db.png)

**Comment by btk999** [comment]
Hello, same problem over here. The issue exists in V1 and V2.

**Comment by Seidlm** [comment]
Hi, this is solved with 2.1 release

**Comment by Utility9298** [comment]
It works fine now :) Thank you very much!!!
