### ISSUE TITLE
Automated script start

### ISSUE THREAD

**Issue by Beppi4U** [Seidlm/PowerShell-Backup-Script#13]
How can i make the script runs once a day?
System is Win10.
Is the backup automaticly zipped? I prefer it unzipped.
Greetings 
Andreas

**Comment by Utility9298** [comment]
Hey, 
for automatic backup: 
https://letmegooglethat.com/?q=powershell+script+automate

For your zip-question: You can easily set $Zip = $false #Zip the Backup Destination... Just look at the code, it is very well documented. 

Please don't forget to close this issue ;)

**Comment by Beppi4U** [comment]
Thanks for the hints!
Andreas
