### ISSUE TITLE
Notification Mail Attachement

### ISSUE THREAD

**Issue by Beppi4U** [Seidlm/PowerShell-Backup-Script#15]
Hello TechGuy!

Thanks for the effort and more thanks for sharing it!
It's pretty cool!
The Script work's fine so far! Just try to understand how it works and expand the functionality a bit!
Added the Lines:
Snip...
##SEND NOTIFICATION MAIL
Write-au2matorLog -Type Info -Text "Send Info Mail about new BackUp to Chef Andreas"

Send-MailMessage -From AndreasEMAIL.com -Subject "Ein neues Inca FehlerLog Backup wurde erstellt" -To AndreasEMAIL.com -Body "INCA FehlerLogdaten Backup wurde erstellt!" -BodyAsHtml -SmtpServer SMTPSERVERADDRESS.com
...endSnip

Works well and send me the notification via email. If it runs on my system there is no need for auth.
If i try to add the "Attachement" -> "LogFile" which is predefined at the beginning of script it's not gonna work!
I'am pretty new to the "power of shell" so forgive me if this is a dumb question to you!
Greetings Andreas

**Comment by Seidlm** [comment]
What is the error message when you try to send with an attachment?
