### ISSUE TITLE
Junction Link giving errors

### ISSUE THREAD

**Issue by IGrayfoxI** [Seidlm/PowerShell-Backup-Script#18]
This is a low priority issue but when I run the script I get the following errors.
Is their away to tell the script to ignore Junction Links?
Adding them to the "ExcludeDirs" does not do anything.
`Skipping "C:\Users\Grayfox\AppData\Local\Application Data" Error: PermissionDenied:
(C:\Users\Grayfo...pplication Data:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\AppData\Local\History" Error: PermissionDenied:
(C:\Users\Grayfox\AppData\Local\History:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\AppData\Local\Microsoft\Windows\INetCache\Content.IE5" Error: PermissionDenied:
(C:\Users\Grayfo...che\Content.IE5:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\AppData\Local\Microsoft\Windows\Temporary Internet Files" Error: PermissionDenied:
(C:\Users\Grayfo... Internet Files:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\AppData\Local\Temporary Internet Files" Error: PermissionDenied:
(C:\Users\Grayfo... Internet Files:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\Application Data" Error: PermissionDenied:
(C:\Users\Grayfox\Application Data:String) [Get-ChildItem], UnauthorizedAccessException
Skipping "C:\Users\Grayfox\Cookies" Error: PermissionDenied:
(C:\Users\Grayfox\Cookies:String) [Get-ChildItem], UnauthorizedAccessException`

Thank you.

**Comment by Seidlm** [comment]
I am not really maintaining this anymore. Maybe one of the Forks has an updated version
