### ISSUE TITLE
Failed to Measure Backupdir

### ISSUE THREAD

**Issue by Hero2799** [Seidlm/PowerShell-Backup-Script#19]
Hi,

ich bekomme leider einen Fehler. Eine Idee wo mein Fehler ist? Nutze die neuste Version.

Failed to Measure Backupdir
Fehler beim Aufrufen der Methode, da [System.IO.FileInfo] keine Methode mit dem Namen “op_Addition” enthält. Fehler beim Aufrufen der Methode, da [System.IO
.FileInfo] keine Methode mit dem Namen “op_Addition” enthält.

**Comment by Utility9298** [comment]
Can you share your command line input?

**Comment by Hero2799** [comment]
Sure.

#Variables
$Destination = "C:\PRINT\Datensicherung\Data\Datenbanken\" #Hierher Kopieren

$Versions = "3" #Wieviele Backups?
$Backupdirs = "C:\Program Files\Lexmark\Solutions\firebird\data\" #Welche Ordner für Backup?
$ExcludeDirs =  #Wird nicht Kopiert

$logPath = "C:\temp\DatenbankBackup"
$LogfileName = "Log" #Log Name
$LoggingLevel = "3" #LoggingLevel, 1=smart, 3=Heavy

$Zip = $true #Zip Backup Destination
$Use7ZIP = $false #7ZIP Module wird installiert https://www.powershellgallery.com/packages/7Zip4Powershell/2.0.0
$UseStaging = $false #nur wenn ZIP benutzt wird, Datei wird nach Staging, gezipt und kopiert zum Ziel, Bandbreite sparen
$StagingPath = "C:\temp\_Staging"

$RemoveBackupDestination = $true #Löschen der Kopien nach dem Zip, nur wenn $Zip true

Powershell Output:

PS C:\Users\admin\Desktop> C:\Users\admin\Desktop\Test.ps1
Starte das Script
Erstelle Backup Dirs und prüfe alle Ordner ob vorhanden
Erstelle Backupdir C:\PRINT\Datensicherung\Data\Datenbanken\\Backup-16-08-2022\
Überprüfe ob BackupDirs vorhanden ist
C:\Program Files\Lexmark\Solutions\firebird\data\ is fine
Vorprüfung war OK, starten mit dem Backup
Ermitle Dateigröße und Überprüfung der Dateien
Failed to Measure Backupdir
Fehler beim Aufrufen der Methode, da [System.IO.FileInfo] keine Methode mit dem Namen "op_Addition" enthält. Der angeforderte Registrierungszugriff ist unzu
lässig.
BAckUpCheck failed so do not try to ZIP
Cleanup Backup Dir
Check if there are more than 3 Zip in the Backupdir

**Comment by Utility9298** [comment]
Ich denke das Problem beginnt bei "Failed to Measure Backupdir" - um welche Dateitypen handelt es sich in dem Ordner? Dein Destination erwähnt Datenbanken?

**Comment by Hero2799** [comment]
Ja es sind .FDB Dateien (FireDB / Firebird)

**Comment by Utility9298** [comment]
Fraglich ob die verwendeten Powershell Befehle für diese Dateien funktionieren - bin sicher kein Experte aber ich vermute das Problem liegt nicht am Backup-Script.

**Comment by Seidlm** [comment]
I am not really maintaining this anymore. Maybe one of the Forks has an updated version
