### ISSUE TITLE
Error running backupscript.ps1

### ISSUE THREAD

**Issue by Whiten561** [Seidlm/PowerShell-Backup-Script#4]
https://github.com/Seidlm/PowerShell-Backup-Script/blob/c8a84dda3032202467ce2358162cd743541fa293/BackupScript.ps1#L203

There appears to be an error in the script posted on GitHub at line 203. The error is "you cannot call a method on a null-valued expression"

Create Backupdir J:\Backups\Backup-2020-05-18-45752\
----------------------
Start the Script
Check if there are more than 15 Directories in the Backupdir
Check if there are more than 15 Zip in the Backupdir
Check if BackupDir and Destination exists
Started the Backup
Count all files and create the Top Level Directories
You cannot call a method on a null-valued expression.
At C:\Users\*****\OneDrive\Documents\WindowsPowerShell\MyScripts\01-BackUpScript1.5.ps1:219 char:3
+         $SumMB += $colItems.Sum.ToString()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

There are 0 Files with  0.00 MB of Files to copy
----------------------
Copied 1 files with 0.00 MB of Files
0 Files could not be copied
Backup duration 0 hours 0 minutes 5 seconds
----------------------
----------------------

**Comment by petruize** [comment]
The same happens to me, any solution? Only the root folder copies me, not the content.

Thanks!

**Comment by dataonthemove** [comment]
Yep, me too... same line ("$SumItems += $colItems.Count ").
I'm not fluent with POSH.. so no clues on my side.
Oddly an older version of the script seems to be working.

**Comment by Seidlm** [comment]
Solved with v2 Release
