### ISSUE TITLE
SendMail issue

### ISSUE THREAD

**Issue by ghost** [Seidlm/PowerShell-Backup-Script#5]
Using your latest version on Server 2012R2 with PS version 4... Got this message after it finished copying.

Send-MailMessage : Cannot validate argument on parameter 'Attachments'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\[redacted]\Desktop\BackupScript.ps1:255 char:131
+ ... TP -attachment $Log
+                    ~~~~
    + CategoryInfo          : InvalidData: (:) [Send-MailMessage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.SendMailMessage

Any suggestions?

**Comment by benoneal89** [comment]
I also received this error, but I did figure out a solution.  Here is what I did!
1.  Below $EmailBody on line 235 add the following variable.  $log = $logPath + "*.log"
2.  On the Send-MailMessage command, add -Attachments $log at the end if it isn't already there.

I hope that makes sense!  If not just let me know and I'll try to attach a screenshot!

**Comment by Seidlm** [comment]
fixed in v2
