### ISSUE TITLE
Error running in PowerShellISE

### ISSUE THREAD

**Issue by WallyZ** [Seidlm/PowerShell-Backup-Script#6]
I ran into an issue that I was able to fix.
I use PowerShellISE so I can interactively work on scripts and run them easily.

At the end of the script, I get:

Exception calling "ReadKey“ with "1“ argument(s): "The method or operation is not implemented.“
At C:\Users\\Downloads\BackupScript.ps1:356 char:1
+ $x = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown“)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NotImplementedException

After some searching, I found that ReadKey does not work in PowerShellISE.
A solution I found that works in PowerShell and PowerShellISE was at
https://stackoverflow.com/questions/20886243/press-any-key-to-continue
I added the following function:

`Function pause ($message)
{
    # Check if running Powershell ISE
    if ($psISE)
    {
        Add-Type -AssemblyName System.Windows.Forms
        [System.Windows.Forms.MessageBox]::Show("$message")
    }
    else
    {
        Write-Host "$message" -ForegroundColor Yellow
        $x = $host.ui.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    }
}`

and replaced the following line from the original script, not in the function:
$x = $host.ui.RawUI.ReadKey(„NoEcho,IncludeKeyDown“)

with
pause "Press any key to close …“

In PowerShellISE it brings up a Windows Message Box which could be pushed to the background and missed by the user.

Works like a charm for me.

**Comment by Seidlm** [comment]
Solved with v2 Release
