### ISSUE TITLE
Win10 Pro script fail when run via task scheduler

### ISSUE THREAD

**Issue by Dergonic** [Seidlm/PowerShell-Backup-Script#7]
Hi

I'm running the last version of the script via the windows Task Scheduler on a Windows 10 pro up-to-date.
Manually (Right clic on the script file, "Run with PowerShell"), the script runs great !

When it runs via the task scheduler (At 1am everyday), script fails with this error (in the log)
"14.07.2020-01:00:07: <Error> <9920> One of the Directories are not available, Script has stopped"
[20200714_Log.log](https://github.com/Seidlm/PowerShell-Backup-Script/files/4917266/20200714_Log.log)

I checked in the script why, and saw the "Check-Dir" function should log the cause (even source or destination is unreachable). But none of the 2 messages are in the log. (Attached, one of the log file.

Other information that may be helpfull
- Source are local files (On C: and D: drives)
- Destination is a remote repository (On a Freenas) mapped in windows (Z:)
- Computer is on, session open and Z: is working well. 

And here is my backup configuration
```
#Variables, only Change here
$Destination = "Z:\BCKP\Asterix" #Copy the Files to this Location
$Staging = "D:\BCKP\staging"
$ClearStaging = $true # When $true, Staging Dir will be cleared
$Versions = "15" #How many of the last Backups you want to keep
$BackupDirs = "C:\Users\Dergonic", "D:\Stream" #What Folders you want to backup

$ExcludeDirs = #This list of Directories will not be copied
($env:SystemDrive + "\Users\.*\AppData\Local"),
($env:SystemDrive + "\Users\.*\AppData\LocalLow")

$LogfileName = "Log" #Log Name
$LoggingLevel = "3" #LoggingLevel only for Output in Powershell Window, 1=smart, 3=Heavy
$Zip = $true #Zip the Backup Destination
$Use7ZIP = $true #Make sure it is installed
$RemoveBackupDestination = $true #Remove copied files after Zip, only if $Zip is true
$UseStaging = $true #only if you use ZIP, than we copy file to Staging, zip it and copy the ZIP to destination, like Staging, and to save NetworkBandwith



#Send Mail Settings
$SendEmail = $false                    # = $true if you want to enable send report to e-mail (SMTP send)
$EmailTo = 'test@domain.com'              #user@domain.something (for multiple users use "User01 &lt;user01@example.com&gt;" ,"User02 &lt;user02@example.com&gt;" )
$EmailFrom = 'from@domain.com'   #matthew@domain 
$EmailSMTP = 'smtp.domain.com' #smtp server adress, DNS hostname.

```

**Comment by Seidlm** [comment]
Solved with v2 Release
