### ISSUE TITLE
Files in the root folder are not being copied

### ISSUE THREAD

**Issue by SerWax** [Seidlm/PowerShell-Backup-Script#8]
Hello,
thank you for your script.

Aside from a small issue with the log attachment (which I solved by declaring the $Log variable, it must have been lost between versions), I have noticed that files in the root folder are not being backed up, while the contents of subfolders all copy correctly.

I.E.:

C:\Folder\1.txt
C:\Folder\Subfolder\2.txt

$BackupDirs = "C:\Folder"

Subfolder and 2.txt get copied
1.txt does not appear in the zip file or the staging folder during execution

**Comment by GutierrezDev** [comment]
Hi @SerWax I have the same problem.
Also I did a little test to verify if solves the problem.
inside the make-backup function I remove this "-Attributes D+!ReparsePoint, D+H+!ReparsePoint -ErrorVariable +errItems -ErrorAction SilentlyContinue" in the first Get-ChildItem - LiteralPath $Backup - recurse.

So i will be like this image. Hope this works for you too.
![image](https://user-images.githubusercontent.com/1899168/93134759-348f4f80-f6a7-11ea-9c53-24448fdc553e.png)
@Seidlm hope this help identifying the problem and solving. I dont know what other problems could happen removing -Attributes D+!ReparsePoint, D+H+!ReparsePoint -ErrorVariable +errItems -ErrorAction SilentlyContinue. Im new to powershell scripting.

**Comment by Dergonic** [comment]
@GutierrezDev, The part you removed contains basically 2 things :

- "-Attributes D+!ReparsePoint, D+H+!ReparsePoint" I just filtering the folder you are listing so it includes any "Directory which is not a ReparsePoint" and all "Hidden directory which is not a ReparsePoint". 
For Reparse point definition, I'll redirect you to google or there (https://jp-andre.pagesperso-orange.fr/junctions.html) as it is out of my own comprehension. 

- "-ErrorVariable +errItems -ErrorAction SilentlyContinue" is only ment to be the way the script handle the errors/exception and the way it is logged.

**Comment by Utility9298** [comment]
i got the same issue too, the script only copies directories to the zip. 

I tried to solve that issue, but no luck so far.

**Comment by Seidlm** [comment]
Solved with v2 Release
