### ISSUE TITLE
Exclude files does not work properly

### ISSUE THREAD

**Issue by thomas-kastner** [Seidlm/PowerShell-Backup-Script#9]
I am using large parts of the Backup-Script for PowerShell
All works well besides I am having trouble to exclude “C:\Program Files (x86)”. I put it into $Exclude and it is there even correct in REGEX format but at the end it does not work ☹. 
Any help or hint would be highly appreciated.
Cheers
Thomas

**Comment by dataonthemove** [comment]
Yeah , me too..

**Comment by Seidlm** [comment]
Solved with v2 Release
